---

- hosts: webservers
  become: 'true'
  tasks:
  - name: Install packages
    yum:
      name: "httpd"
      state: "present"
  - name: Start Apache Server
    service:
      name: httpd
      state: started
      enabled: 'true'
  - name: Deploy
    copy:
      src: index.html
      dest: var/www/html
