  
---
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
   containers:  
    - name: ansible
      image: ansible_main_ansible
      command: ["tail", "-f", "/dev/null"]  
      imagePullPolicy: Always 
    - name: jnlp
      image: jenkins/jnlp-slave
      imagePullPolicy: Always
      


