---
- name: This is a hello-world example
  hosts: localhost
  tasks:
    - name: Create a file called '/tmp/test.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/test.txt
