---
- hosts: localhost
  gather_facts: 'false'

  tasks:
    - name: Deploy my app secrets.
      k8s:
        kubeconfig: '~/config'
        state: present
    - name: Get a list of all pods from any namespace
      k8s_facts:
        kind: Pod
      register: pod_list
