- hosts: 192.168.13.64
  gather_facts: 'false'
  tasks:
   - name: Create a k8s namespace
     k8s:
      kubeconfig: '~/.kube/config'
      name: testing1
      api_version: v1
      kind: Namespace
      state: present
      state: present
