---
- name: This is a hello-world example
  hosts: ansibleclient01.local
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      community.kubernetes.k8s_info:
        kind: Pod
      register: pod_list
