- hosts: localhost
  gather_facts: 'false'
  tasks:
  - name: Create a Service object from an inline definition
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: web1
          namespace: jenkins
          labels:
            app: galaxy
            service: web
        spec:
          selector:
            app: galaxy
            service: web
          ports:
          - protocol: TCP
            targetPort: 8001
            name: port-8001-tcp
            port: 8001
