apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: jenkins
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: hello

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
